### ISSUE TITLE
For the love of vs can we get some documentation?

### ISSUE THREAD

**Issue by jdgeier** [Brightspace/D2L.Security.OAuth2#112]
I've been reading the code and trying to puzzle out what is needed to get with working and I am flabergasted. I've tried to look at the test code and get it integrated with my StartUp.Auth.cs but I'm banging my head against the wall.

**Comment by j3parker** [comment]
Hey!

Are you looking to integrate with Brightspace? If so you should be able to use any third party C# OAuth library, they should be compatible with us (if not, either reach out to customer support or create an issue in this repo.) For example, you could try [DotNetOpenAuth](https://github.com/DotNetOpenAuth/DotNetOpenAuth).

This library is mostly used internally at D2L to implement OAuth 2.0, and it supports the grant type (`jwt_bearer`) that our servers use to communicate with each-other. We don't make those features available to clients at this time, so the library won't be very useful (and we don't have any public documentation.) It's open source because we'd generally like to make more things open source and if we open source more of our backend we'll need to open source this anyway.

You'll be using a different grant type - `authorization_code` - and we didn't implement an SDK for that because there are already plenty of open source 3rd party libraries for that :)

**Comment by j3parker** [comment]
From the README

> .NET libraries for integrating with Brightspace OAuth 2.0. These libraries implement D2L-specific functionality (like validating access tokens, manipulating scope, etc.) and the jwt-bearer grant. **(Most third-party users should use a cross-platform OAuth 2.0 library of their choosing (see the "Client Libraries" section on this page for examples.)**

Not super obvious, sorry for the confusion.
